// Auto-generated from iNaturalist observation data
// Query: research-grade butterfly observations by city bounding box
// Generated: 2026-04-08

const LOCATIONS = [
  {
    "id": "poway",
    "name": "Poway",
    "habitat": "Inland chaparral & sage scrub"
  },
  {
    "id": "san-diego",
    "name": "San Diego",
    "habitat": "Coastal urban"
  },
  {
    "id": "encinitas",
    "name": "Encinitas",
    "habitat": "North coastal bluffs & lagoons"
  },
  {
    "id": "escondido",
    "name": "Escondido",
    "habitat": "Inland valley & chaparral"
  },
  {
    "id": "ramona",
    "name": "Ramona",
    "habitat": "Grassland & oak woodland"
  },
  {
    "id": "julian",
    "name": "Julian",
    "habitat": "Mountain pine-oak forest"
  },
  {
    "id": "borrego-springs",
    "name": "Borrego Springs",
    "habitat": "Anza-Borrego desert"
  },
  {
    "id": "chula-vista",
    "name": "Chula Vista",
    "habitat": "South Bay coastal & scrub"
  },
  {
    "id": "el-cajon",
    "name": "El Cajon",
    "habitat": "Inland valley & foothill scrub"
  },
  {
    "id": "oceanside",
    "name": "Oceanside",
    "habitat": "North coastal"
  }
];

// Observation counts per city: { "city-id": { "Scientific name": count } }
const LOCATION_DATA = {
  "poway": {
    "Danaus plexippus": 92,
    "Apodemia mormo virgulti": 70,
    "Agraulis vanillae incarnata": 44,
    "Papilio cresphontes": 42,
    "Nymphalis antiopa": 38,
    "Junonia coenia grisea": 38,
    "Leptotes marina": 37,
    "Hylephila phyleus muertovalle": 29,
    "Erynnis funeralis": 28,
    "Vanessa cardui": 21,
    "Papilio rutulus": 17,
    "Strymon melinus pudica": 16,
    "Papilio zelicaon": 16,
    "Papilio eurymedon": 16,
    "Anthocharis sara sara": 16,
    "Limenitis lorquini": 15,
    "Pontia protodice": 15,
    "Adelpha bredowii californica": 15,
    "Pieris rapae": 11,
    "Glaucopsyche lygdamus australis": 11,
    "Poanes melane": 10,
    "Vanessa atalanta rubria": 8,
    "Coenonympha californica californica": 7,
    "Icaricia acmon acmon": 7,
    "Vanessa annabella": 6,
    "Euphilotes bernardino": 6,
    "Callophrys dumetorum affinis": 6,
    "Callophrys augustinus": 5,
    "Hemiargus ceraunus gyas": 5,
    "Erynnis tristis": 4,
    "Heliopetes ericetorum": 4,
    "Ochlodes sylvanoides": 4,
    "Ochlodes agricola": 3,
    "Colias eurytheme": 1,
    "Vanessa virginiensis": 2,
    "Phoebis sennae marcellina": 2,
    "Celastrina ladon echo": 2,
    "Satyrium sylvinus sylvinus": 2,
    "Hemiargus isola alce": 2,
    "Speyeria callippe comstocki": 2,
    "Danaus gilippus thersippus": 1,
    "Brephidium exila": 1,
    "Polygonia satyrus": 1,
    "Apodemia mormo": 1,
    "Erynnis propertius": 1,
    "Everes amyntula": 1,
    "Calephelis nemesis californica": 1,
    "Strymon istapa": 1,
    "Calephelis wrighti": 1,
    "Pyrgus albescens": 1
  },
  "san-diego": {
    "Danaus plexippus": 1494,
    "Nymphalis antiopa": 666,
    "Hylephila phyleus muertovalle": 568,
    "Agraulis vanillae incarnata": 324,
    "Pieris rapae": 311,
    "Papilio cresphontes": 280,
    "Leptotes marina": 259,
    "Poanes melane": 172,
    "Papilio zelicaon": 171,
    "Strymon melinus pudica": 156,
    "Phoebis sennae marcellina": 140,
    "Papilio rutulus": 128,
    "Vanessa cardui": 128,
    "Vanessa annabella": 106,
    "Vanessa atalanta rubria": 99,
    "Ochlodes sylvanoides": 82,
    "Limenitis lorquini": 77,
    "Erynnis funeralis": 57,
    "Junonia coenia grisea": 52,
    "Apodemia mormo virgulti": 48,
    "Lerodea eufala": 39,
    "Pontia protodice": 26,
    "Brephidium exila": 21,
    "Satyrium sylvinus sylvinus": 20,
    "Anthocharis sara sara": 16,
    "Calephelis nemesis californica": 16,
    "Colias eurytheme": 10,
    "Vanessa virginiensis": 13,
    "Danaus gilippus thersippus": 12,
    "Hemiargus ceraunus gyas": 12,
    "Nathalis iole": 10,
    "Erynnis tristis": 9,
    "Pyrgus albescens": 8,
    "Euphilotes bernardino": 7,
    "Everes amyntula": 6,
    "Glaucopsyche lygdamus australis": 5,
    "Icaricia acmon acmon": 5,
    "Papilio eurymedon": 4,
    "Adelpha bredowii californica": 4,
    "Callophrys augustinus": 2,
    "Polites sabuleti sabuleti": 2,
    "Chlosyne californica": 2,
    "Hemiargus isola alce": 2,
    "Strymon istapa": 2,
    "Copaeodes aurantiaca": 2,
    "Battus philenor": 1,
    "Euphydryas chalcedona": 1,
    "Atalopedes campestris": 1,
    "Celastrina ladon echo": 1,
    "Ochlodes agricola": 1,
    "Satyrium saepium": 1,
    "Phyciodes mylitta": 1,
    "Euphydryas editha quino": 1,
    "Heliopetes ericetorum": 1,
    "Eurema nicippe": 1,
    "Lycaeides melissa paradoxa": 1,
    "Pontia beckerii": 1,
    "Callophrys dumetorum affinis": 1,
    "Icaricia icaroides evius": 1
  },
  "encinitas": {
    "Danaus plexippus": 413,
    "Hylephila phyleus muertovalle": 268,
    "Poanes melane": 165,
    "Leptotes marina": 160,
    "Nymphalis antiopa": 156,
    "Agraulis vanillae incarnata": 150,
    "Pieris rapae": 111,
    "Papilio cresphontes": 103,
    "Phoebis sennae marcellina": 99,
    "Papilio zelicaon": 73,
    "Vanessa cardui": 62,
    "Strymon melinus pudica": 57,
    "Vanessa annabella": 43,
    "Junonia coenia grisea": 33,
    "Papilio rutulus": 32,
    "Erynnis funeralis": 29,
    "Vanessa atalanta rubria": 26,
    "Panoquina errans": 24,
    "Colias eurytheme": 23,
    "Limenitis lorquini": 22,
    "Icaricia acmon acmon": 15,
    "Pontia protodice": 13,
    "Glaucopsyche lygdamus australis": 12,
    "Battus philenor": 11,
    "Brephidium exila": 10,
    "Danaus gilippus thersippus": 9,
    "Satyrium sylvinus sylvinus": 8,
    "Erynnis tristis": 7,
    "Vanessa virginiensis": 5,
    "Euphilotes bernardino": 5,
    "Nathalis iole": 4,
    "Papilio eurymedon": 4,
    "Lerodea eufala": 4,
    "Hemiargus ceraunus gyas": 4,
    "Apodemia mormo virgulti": 4,
    "Calephelis nemesis californica": 4,
    "Heliopetes ericetorum": 2,
    "Eurema nicippe": 2,
    "Adelpha bredowii californica": 2,
    "Strymon istapa": 2,
    "Nymphalis californica": 1,
    "Polygonia satyrus": 1,
    "Papilio polyxenes coloro": 1,
    "Callophrys augustinus": 1,
    "Anthocharis sara sara": 1,
    "Ochlodes sylvanoides": 1,
    "Zerene eurydice": 1,
    "Hemiargus isola alce": 1
  },
  "escondido": {
    "Danaus plexippus": 44,
    "Agraulis vanillae incarnata": 30,
    "Nymphalis antiopa": 27,
    "Hylephila phyleus muertovalle": 17,
    "Papilio cresphontes": 16,
    "Junonia coenia grisea": 10,
    "Papilio rutulus": 8,
    "Pieris rapae": 6,
    "Vanessa cardui": 5,
    "Vanessa atalanta rubria": 5,
    "Vanessa annabella": 4,
    "Limenitis lorquini": 3,
    "Strymon melinus pudica": 3,
    "Pontia protodice": 3,
    "Leptotes marina": 3,
    "Apodemia mormo virgulti": 3,
    "Phoebis sennae marcellina": 2,
    "Danaus gilippus thersippus": 2,
    "Papilio eurymedon": 2,
    "Erynnis tristis": 2,
    "Adelpha bredowii californica": 2,
    "Nathalis iole": 1,
    "Brephidium exila": 1,
    "Anthocharis sara sara": 1,
    "Euphilotes bernardino": 1,
    "Erynnis funeralis": 1,
    "Lerodea eufala": 1,
    "Poanes melane": 1,
    "Pyrgus albescens": 1
  },
  "ramona": {
    "Pontia protodice": 9,
    "Danaus plexippus": 8,
    "Nymphalis antiopa": 6,
    "Vanessa cardui": 3,
    "Hylephila phyleus muertovalle": 3,
    "Papilio eurymedon": 3,
    "Junonia coenia grisea": 3,
    "Papilio rutulus": 2,
    "Vanessa annabella": 2,
    "Strymon melinus pudica": 2,
    "Pieris rapae": 2,
    "Colias eurytheme": 2,
    "Erynnis funeralis": 2,
    "Vanessa atalanta rubria": 1,
    "Agraulis vanillae incarnata": 1,
    "Euphyes vestris harbisoni": 1,
    "Callophrys augustinus": 1,
    "Anthocharis sara sara": 1,
    "Satyrium saepium": 1,
    "Leptotes marina": 1,
    "Erynnis tristis": 1,
    "Eurema nicippe": 1,
    "Adelpha bredowii californica": 1,
    "Hemiargus ceraunus gyas": 1,
    "Apodemia mormo virgulti": 1,
    "Papilio cresphontes": 1,
    "Poanes melane": 1,
    "Speyeria callippe comstocki": 1,
    "Pyrgus albescens": 1
  },
  "julian": {
    "Adelpha bredowii californica": 19,
    "Junonia coenia grisea": 18,
    "Pieris rapae": 11,
    "Lycaena xanthoides": 11,
    "Vanessa cardui": 9,
    "Erynnis propertius": 9,
    "Icaricia acmon acmon": 8,
    "Pyrgus albescens": 8,
    "Pontia protodice": 7,
    "Phyciodes mylitta": 7,
    "Papilio rutulus": 6,
    "Euphilotes bernardino": 6,
    "Erynnis tristis": 6,
    "Apodemia mormo virgulti": 6,
    "Callophrys dumetorum affinis": 6,
    "Vanessa virginiensis": 5,
    "Papilio eurymedon": 5,
    "Erynnis funeralis": 5,
    "Ochlodes sylvanoides": 5,
    "Hemiargus ceraunus gyas": 5,
    "Celastrina ladon echo": 4,
    "Nathalis iole": 3,
    "Colias eurytheme": 3,
    "Satyrium auretorum spadix": 3,
    "Danaus plexippus": 2,
    "Nymphalis californica": 2,
    "Anthocharis sara sara": 2,
    "Chlosyne gabbii": 2,
    "Icaricia lupini monticola": 2,
    "Euphydryas chalcedona": 1,
    "Strymon melinus pudica": 1,
    "Danaus gilippus thersippus": 1,
    "Glaucopsyche lygdamus australis": 1,
    "Nymphalis antiopa": 1,
    "Satyrium saepium": 1,
    "Leptotes marina": 1,
    "Hesperia juba": 1,
    "Lycaeides melissa paradoxa": 1,
    "Colias harfordii": 1,
    "Agathymus stephensi": 1,
    "Icaricia icaroides evius": 1,
    "Lycaena helloides": 1
  },
  "borrego-springs": {
    "Vanessa cardui": 124,
    "Dymasia dymas imperialis": 66,
    "Danaus gilippus thersippus": 30,
    "Anthocharis sara sara": 16,
    "Erynnis funeralis": 13,
    "Pontia protodice": 11,
    "Chlosyne californica": 11,
    "Calephelis wrighti": 8,
    "Callophrys dumetorum affinis": 8,
    "Danaus plexippus": 7,
    "Leptotes marina": 6,
    "Hemiargus ceraunus gyas": 6,
    "Apodemia mormo mejicanus": 6,
    "Euphydryas chalcedona": 5,
    "Nathalis iole": 5,
    "Colias eurytheme": 5,
    "Strymon melinus pudica": 3,
    "Pontia sisymbrii": 3,
    "Junonia coenia grisea": 3,
    "Hylephila phyleus muertovalle": 2,
    "Erynnis brizo lacustra": 2,
    "Papilio polyxenes coloro": 2,
    "Libytheana carinenta": 2,
    "Atlides halesus corcorani": 2,
    "Heliopetes ericetorum": 2,
    "Apodemia mormo virgulti": 2,
    "Anthocharis cethura": 2,
    "Systasea zampa": 2,
    "Icaricia acmon acmon": 2,
    "Vanessa virginiensis": 1,
    "Agraulis vanillae incarnata": 1,
    "Nymphalis californica": 1,
    "Vanessa annabella": 1,
    "Brephidium exila": 1,
    "Pieris rapae": 1,
    "Apodemia mormo": 1,
    "Lerodea eufala": 1,
    "Eurema nicippe": 1,
    "Zerene eurydice": 1,
    "Hemiargus isola alce": 1,
    "Thessalia leanira wrighti": 1,
    "Strymon istapa": 1,
    "Pontia beckerii": 1,
    "Agathymus stephensi": 1,
    "Ministrymon leda": 1,
    "Pyrgus albescens": 1,
    "Copaeodes aurantiaca": 1
  },
  "chula-vista": {
    "Danaus plexippus": 127,
    "Hylephila phyleus muertovalle": 68,
    "Nymphalis antiopa": 51,
    "Papilio cresphontes": 46,
    "Papilio zelicaon": 41,
    "Pieris rapae": 31,
    "Leptotes marina": 22,
    "Vanessa annabella": 20,
    "Agraulis vanillae incarnata": 18,
    "Strymon melinus pudica": 16,
    "Poanes melane": 15,
    "Vanessa cardui": 14,
    "Coenonympha californica californica": 14,
    "Everes amyntula": 13,
    "Junonia coenia grisea": 13,
    "Phoebis sennae marcellina": 12,
    "Vanessa atalanta rubria": 12,
    "Brephidium exila": 9,
    "Limenitis lorquini": 6,
    "Erynnis funeralis": 6,
    "Papilio rutulus": 5,
    "Anthocharis sara sara": 5,
    "Satyrium sylvinus sylvinus": 5,
    "Lerodea eufala": 5,
    "Danaus gilippus thersippus": 4,
    "Vanessa virginiensis": 2,
    "Pontia protodice": 2,
    "Hemiargus ceraunus gyas": 2,
    "Strymon istapa": 2,
    "Pyrgus albescens": 2,
    "Nathalis iole": 1,
    "Papilio eurymedon": 1,
    "Pontia sisymbrii": 1,
    "Euphilotes bernardino": 1,
    "Ochlodes sylvanoides": 1,
    "Adelpha bredowii californica": 1,
    "Panoquina errans": 1,
    "Apodemia mormo virgulti": 1,
    "Icaricia acmon acmon": 1
  },
  "el-cajon": {
    "Danaus plexippus": 262,
    "Hylephila phyleus muertovalle": 77,
    "Papilio cresphontes": 63,
    "Pieris rapae": 42,
    "Nymphalis antiopa": 41,
    "Leptotes marina": 34,
    "Junonia coenia grisea": 33,
    "Agraulis vanillae incarnata": 30,
    "Vanessa cardui": 26,
    "Vanessa atalanta rubria": 26,
    "Strymon melinus pudica": 23,
    "Lerodea eufala": 16,
    "Vanessa annabella": 13,
    "Phoebis sennae marcellina": 9,
    "Papilio rutulus": 8,
    "Pontia protodice": 8,
    "Papilio eurymedon": 7,
    "Apodemia mormo virgulti": 6,
    "Colias eurytheme": 4,
    "Papilio zelicaon": 4,
    "Glaucopsyche lygdamus australis": 4,
    "Erynnis funeralis": 4,
    "Icaricia acmon acmon": 4,
    "Poanes melane": 4,
    "Danaus gilippus thersippus": 3,
    "Brephidium exila": 3,
    "Pyrgus albescens": 3,
    "Ochlodes agricola": 2,
    "Callophrys augustinus": 2,
    "Erynnis tristis": 2,
    "Callophrys dumetorum affinis": 2,
    "Nymphalis californica": 1,
    "Limenitis lorquini": 1,
    "Polites sabuleti sabuleti": 1,
    "Ochlodes sylvanoides": 1,
    "Hemiargus ceraunus gyas": 1,
    "Colias harfordii": 1,
    "Lycaena hermes": 1,
    "Speyeria callippe comstocki": 1
  },
  "oceanside": {
    "Danaus plexippus": 105,
    "Papilio cresphontes": 50,
    "Nymphalis antiopa": 42,
    "Hylephila phyleus muertovalle": 39,
    "Leptotes marina": 34,
    "Pieris rapae": 29,
    "Papilio zelicaon": 25,
    "Vanessa cardui": 22,
    "Agraulis vanillae incarnata": 17,
    "Poanes melane": 17,
    "Strymon melinus pudica": 15,
    "Vanessa atalanta rubria": 9,
    "Phoebis sennae marcellina": 8,
    "Vanessa annabella": 6,
    "Limenitis lorquini": 6,
    "Panoquina errans": 6,
    "Papilio rutulus": 5,
    "Brephidium exila": 4,
    "Erynnis funeralis": 4,
    "Apodemia mormo virgulti": 3,
    "Junonia coenia grisea": 3,
    "Danaus gilippus thersippus": 2,
    "Pontia protodice": 2,
    "Satyrium sylvinus sylvinus": 2,
    "Coenonympha californica californica": 2,
    "Vanessa virginiensis": 1,
    "Nathalis iole": 1,
    "Atalopedes campestris": 1,
    "Papilio eurymedon": 1,
    "Polygonia satyrus": 1,
    "Glaucopsyche lygdamus australis": 1,
    "Anthocharis sara sara": 1,
    "Hemiargus ceraunus gyas": 1,
    "Strymon istapa": 1,
    "Pyrgus albescens": 1
  }
};
